project_dbt:
  outputs:
    dev:
      dataset: dbt_gustavo
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /PASTA_DIRETORIO/key.json
      location: us-west1
      method: service-account
      priority: interactive
      project: project-dbt-410613
      threads: 1
      type: bigquery
  target: dev